---
- name: 查看 docker 是否安装
  shell: docker info
  register: docker_install_info
  ignore_errors: yes

- name: 查看 kubeadm 是否安装
  shell: kubeadm version
  register: kubeadm_install_info
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: True
  become: True

- name: Install pip3 package
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pip
      - git
      - rsync
      - python3-virtualenv
      - iptables
      - sg3-utils-udev
      - ntp
      - jq
      - ipvsadm
      - ipmitool
      - ceph-fuse

- name: remove apparmor
  apt:
    state: absent
    name: "{{ packages }}"
  vars:
    packages:
      - apparmor
      - ufw

- name: Install kube ansible package
  pip:
    name: "{{ package }}"
  vars:
    package:
      - kubernetes
      - openshift
      - docker

- name: 安装docker
  apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
  when:
    - docker_install_info is not success

- name: 确认 Docker 配置是否有修改
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  register: configuration_result

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- name: 启动/重启 Docker
  service:
    name: docker
    state: restarted
    enabled: yes
  when: 
  - configuration_result.changed
  
- name: 设置 Docker 开机自启
  service:
    name: docker
    state: started
    enabled: yes

- name: 安装 kubeadm kubelet kubectl
  apt: 
    name:
    - "kubectl=1.23.5-00"
    - "kubelet=1.23.5-00"
    - "kubeadm=1.23.5-00"
    state: present
  when:
    - kubeadm_install_info is not success

- name: 安装 etcdctl 工具
  apt:
    name:
    - etcd-client
    state: present

- name: 配置 kubectl 命令行自动补全
  shell: kubectl completion bash > /usr/share/bash-completion/completions/kubectl

- name: Docker Login
  docker_login:
    registry: "{{ docker_register_address }}"
    username: "{{ harbor_username }}"
    debug: true
    password: "{{ harbor_password }}"
  when:
    - enable_docker_auth | bool
