---
# tasks file for baremetal
- name: set timezone to Asia/Shanghai
  timezone:
    name: "Asia/Shanghai"

- name: set ansible_execution_server
  set_fact:
    ansible_execution_server: "{{ inventory_hostname }}"
  delegate_to: localhost
  run_once: True

- name: set hostname
  hostname:
    name: "{{ hostvars[inventory_hostname]['hostname'] }}"

- name: Ensure hostname does not point to 127.0.1.1 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1\\b.*\\s{{ ansible_hostname }}\\b"
    state: absent
  become: True

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in groups['baremetal'] %}
        {% set api_interface = hostvars[host]['api_interface'] %}
        {% if 'ansible_' + api_interface in hostvars[host] %}
        {% set hostnames = [hostvars[host]['ansible_nodename'], hostvars[host]['ansible_hostname']] %}
        {{ hostvars[host]['ansible_' + api_interface]['ipv4']['address'] }} {{ hostnames | unique | join(' ') }}
        {% endif %}
        {% endfor %}
  become: True

- name: Update apt cache
  apt:
    update_cache: yes
  become: True

- name: Set firewall default policy
  become: True
  ufw:
    state: disabled
    policy: allow
  ignore_errors: yes

- name: Clear all iptables rule
  command: iptables -F -t {{ item }}
  with_list:
    - filter
    - nat
    - mangle
    - raw

- name: Clear all iptables custom chains
  command: iptables -X -t {{ item }}
  with_list:
    - filter
    - nat
    - mangle
    - raw

- name: remove apparmor
  apt:
    state: absent
    name: "{{ packages }}"
  vars:
    packages:
      - apparmor



- name: Install kube ansible package
  pip:
    name: "{{ package }}"
  vars:
    package:
      - kubernetes
      - openshift

- name: Install ansible galaxy
  shell: ansible-galaxy collection install cloud.common
  run_once: True
  delegate_to: "localhost"

- name: Install ansible galaxy
  shell: ansible-galaxy collection install kubernetes.core
  run_once: True
  delegate_to: "localhost"
