---
- import_tasks: install_package.yaml

- import_tasks: mount_cephfs.yaml
  when:
    - enable_ceph | bool

- import_tasks: set_voi_data_device.yaml
  when: only_deploy_voi | bool
  run_once: True

- import_tasks: set_voi_virt_nic.yaml
  when: only_deploy_voi | bool
  run_once: True

- name: 获取可分配的大页数量
  set_fact:
    hugepages_total: "{{ (ansible_memtotal_mb  * (1 - hugepages_reserved_rate) // 2) | int }}"
  when:
    - enable_hugepages | bool

- name: 获取可分配的大页数量
  debug:
    msg: "{{ hugepages_total }}"
  when:
    - enable_hugepages | bool

- name: 分配大页内存
  shell: echo {{ hugepages_total }} > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
  when:
    - enable_hugepages | bool
