---
- import_tasks: install_package.yaml

- import_tasks: mount_cephfs.yaml
  when:
    - enable_ceph | bool

- import_tasks: set_voi_data_device.yaml
  when: only_deploy_voi | bool
  run_once: True

- import_tasks: set_voi_virt_nic.yaml
  when: only_deploy_voi | bool
  run_once: True
