- name: 添加 Docker GPG 公钥
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: 添加 Docker apt 仓库
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: 更新 apt 仓库
  apt:
    upgrade: yes
    update_cache: yes

- name: 安装docker
  apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: 确认 Docker 配置是否有修改
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  register: configuration_result

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- name: 启动/重启 Docker
  service:
    name: docker
    state: restarted
    enabled: yes
  when: 
  - configuration_result.changed
  
- name: 设置 Docker 开机自启
  service:
    name: docker
    state: started
    enabled: yes