- name: 安装 apt-transport-https
  apt:
    name:
    - apt-transport-https
    state: present

- name: 添加 apt key gpg
  shell: curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | apt-key add -

- name: 添加 Kubernetes apt 仓库
  apt_repository:
    repo: "deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main"
    state: present

- name: 更新 apt 仓库
  apt:
    upgrade: yes
    update_cache: yes

- name: 安装 kubeadm kubelet kubectl
  apt: 
    name:
    - "kubectl=1.23.5-00"
    - "kubelet=1.23.5-00"
    - "kubeadm=1.23.5-00"
    state: present

- name: 安装 etcdctl 工具
  apt:
    name:
    - etcd-client
    state: present

- name: 配置 kubectl 命令行自动补全
  shell: kubectl completion bash > /usr/share/bash-completion/completions/kubectl