affinity: {}
containerSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
emqxAclConfig: |
  {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}. {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}. {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}. {allow, all}.
emqxConfig:
  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: ip
  EMQX_CLUSTER__K8S__APISERVER: https://172.18.28.193:6443
  EMQX_CLUSTER__K8S__APP_NAME: '{{ .Release.Name }}'
  EMQX_CLUSTER__K8S__NAMESPACE: '{{ .Release.Namespace }}'
  EMQX_CLUSTER__K8S__SERVICE_NAME: '{{ .Release.Name }}-headless'
  # EMQX_CLUSTER__K8S__SUFFIX: svc.cluster.local
  EMQX_NAME: '{{ .Release.Name }}'
  EMQX_MANAGEMENT__LISTENER__HTTP: '8082'
emqxLicenseSecretName: null
emqxLoadedModules: |
  {emqx_mod_acl_internal, true}. {emqx_mod_presence, true}. {emqx_mod_trace, false}. {emqx_mod_slow_subs, false}. {emqx_mod_delayed, false}. {emqx_mod_rewrite, false}. {emqx_mod_subscription, false}. {emqx_mod_topic_metrics, false}.
emqxLoadedPlugins: |
  {emqx_management, true}. {emqx_recon, true}. {emqx_retainer, true}. {emqx_dashboard, true}. {emqx_telemetry, true}. {emqx_rule_engine, true}. {emqx_bridge_mqtt, false}.
extraArgs: []
extraEnv: []
extraEnvFrom: []
extraVolumeMounts: []
extraVolumes: []
image:
  pullPolicy: IfNotPresent
  repository: emqx/emqx
  tag: 4.4.3
ingress:
  annotations: {}
  dashboard:
    annotations: {}
    enabled: false
    hosts:
    - dashboard.emqx.local
    path: /
    tls: []
  mgmt:
    annotations: {}
    enabled: false
    hosts:
    - api.emqx.local
    path: /
    tls: []
  wss:
    annotations: {}
    enabled: false
    hosts:
    - wss.emqx.local
    path: /mqtt
    tls: []
initContainers: {}
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 20Mi
  storageClass: general
podManagementPolicy: Parallel
podSecurityContext:
  enabled: true
  fsGroup: 1000
  fsGroupChangePolicy: Always
  runAsUser: 1000
  supplementalGroups:
  - 1000
recreatePods: false
replicaCount: 3
resources: {}
service:
  annotations: {}
  dashboard: 18083
  externalIPs: []
  loadBalancerSourceRanges: []
  mgmt: 8082
  mqtt: 1883
  mqttssl: 8883
  nodePorts:
    dashboard: null
    dashboardtls: null
    mgmt: null
    mqtt: null
    mqttssl: null
    ws: null
    wss: null
  type: ClusterIP
  ws: 8083
  wss: 8084
tolerations: []
hostNetwork: true