---
btserver_image_tag: "{{ kube_image_tag }}"
btserver_image_repository: "{{ kube_image_repository }}/btserver"
btserver_image_repository_track: "{{ kube_image_repository }}/btserver_track"
btserver_pod_replicaCount: "{% if groups['btserver'] | length > 2 %}2{% else %}1{% endif %}"

