---
- name: 添加私有仓库 hostname 信息到 hosts 文件中
  blockinfile:
    path: /etc/hosts
    block: |-
       {{ docker_register_address }} {{ docker_register_domain }}
    state: present
    create: yes
    backup: yes

- name: dpkg install docker
  shell: "dpkg -i {{ docker_dpkg_path }}/*.deb"
  when:
    - ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: rpm install docker
  shell: "rpm -ivh {{ docker_dpkg_path }}/*.rpm"
  when:
    - ansible_distribution == 'openEuler'
  ignore_errors: true

- name: 创建 /etc/docker 目录
  become: true
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: 确认 Docker 配置是否有修改
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644
  register: configuration_result

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- name: 启动/重启 Docker
  service:
    name: docker
    state: restarted
    enabled: yes
  when: 
  - configuration_result.changed
