---
- name: dpkg install docker
  shell: "dpkg -i {{ docker_dpkg_path }}/*.deb"
  when:
    - ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: rpm install docker
  shell: "rpm -ivh {{ docker_dpkg_path }}/*.rpm"
  when:
    - ansible_distribution == 'openEuler'
  ignore_errors: true

- name: 启动/重启 Docker
  service:
    name: docker
    state: restarted
    enabled: yes
