- include_tasks: chrony.yaml

- name: 查看 docker 是否安装
  shell: docker info
  register: docker_install_info
  ignore_errors: true

- import_tasks: install_docker.yaml
  run_once: True
  delegate_to: "{{ groups['baremetal'][0] }}"
  when:
    - docker_install_info is not success

- name: Ubuntu get offline info
  docker_container_info:
    name: offline-deb-repo
  register: offline_info
  delegate_to: "{{ groups['baremetal'][0] }}"
  when:
    - ansible_distribution == "Ubuntu"

- name: openEuler get offline info
  docker_container_info:
    name: openeuler-offline-rpm-repo
  register: offline_info
  delegate_to: "{{ groups['baremetal'][0] }}"
  when:
    - ansible_distribution == "openEuler"

- name: get registry info
  docker_container_info:
    name: registry
  register: registry_info
  delegate_to: "{{ groups['baremetal'][0] }}"

- import_tasks: container_prepare.yaml
  run_once: True
  delegate_to: "{{ groups['baremetal'][0] }}"
  when: not offline_info.exists or not registry_info.exists

- import_tasks: baremetal_prepare.yaml
