- name: 创建 trochilus values 目录
  file:
    name: /etc/kubernetes/plugins/trochilus
    state: directory

- name: 复制 trochilus charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "trochilus"

- name: 生成 trochilus values.yml
  template:
    src: custom-values-trochilus.yaml.j2
    dest: /etc/kubernetes/plugins/trochilus/values.yaml
    owner: root
    mode: 0644

- name: Install trochilus helm charts
  kubernetes.core.helm:
    atomic: no
    name: trochilus
    chart_ref: "{{ helm_charts_dir }}/trochilus"
    values_files:
      - /etc/kubernetes/plugins/trochilus/values.yaml
    state: present 
    wait: yes
    wait_timeout: "{{ helm_wait_timeout }}"
    release_namespace: "{{ helm_install_namespace }}"
