--- 
- name: mkdir node history dir
  file:
    state: directory
    path: "{{ netcheck_path }}"
    mode: 755
  delegate_to: "{{ groups.allnodes[0] }}"
  run_once: true

- name: delete ping and iperf3 output file
  file:
    path: "{{ netcheck_path }}/{{ item }}"
    state: absent
  with_items:
    - "echoping.yml"
    - "echoiperf3.yml"
  delegate_to: "{{ groups.allnodes[0] }}"
  run_once: true

- name: Check network ping
  ansible_ping:
    ipaddress: "{% for host in groups['allnodes'] %}{{ item | filter_address(host) }}_{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"
    interface: "{{ item | filter_interface_name }}"
    nettype: "{{ item }}"
    times: 3
  with_items: "{{ ping_interface }}"
  register: res_ping_reg

- name: Handler troila netcard params
  run_ping: 
    res_ping_reg_res: "{{ res_ping_reg.results }}"
  register: handler_params_reg

- name: set ping vars fact
  set_fact:
    ping_params_reg: "{{ handler_params_reg.param_ping_res }}"

