---

- name: Restart samba service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  become: True
  with_items:
    - "nmbd"
    - "smbd"
  when: 
    - ansible_distribution == "Ubuntu"

- name: Restart samba service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  become: True
  with_items:
    - "nmb"
    - "smb"
  when: 
    - ansible_distribution == "openEuler"