apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-etc
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.enable_ceph }}
  {{ .Values.secret.rbd_secret_uuid }}.xml: |
     <secret ephemeral='no' private='no'>
     <uuid>{{ .Values.secret.rbd_secret_uuid }}</uuid>
     <usage type='ceph'>
     <name>{{ .Values.secret.secret_user }}</name>
     </usage>
     </secret>

  {{ .Values.secret.rbd_secret_uuid }}.base64: |
    {{ .Values.secret.ceph_admin_keyring }}
  {{- end }}

  libvirtd.conf: |
    listen_tcp = 1
    listen_tls = 0
    auth_tcp = "none"
    tcp_port = "16514"
    ca_file = ""
    log_level = 3
    log_outputs = "3:file:/var/log/libvirt/libvirtd.log"

  qemu.conf: |
    security_driver = "none"
    security_default_confined = 0
    user="root"
    group="root"

  vdi_conf.ini: |
    [common]
    log_level=0
    mode=64
    
    [display]
    full_stream=0
    high_band=20000
    middle_band=10000
    low_band=1000
    high_fps=25
    middle_fps=10
    low_fps=10
    mode_full_cnt=3
    mode_pic_cnt=5
    mode_detect_cnt=6
    
    [display.mix264]
    level=0
    profile=1
    drop=0
    qp_min={{ .Values.libvirt_qp_min }}
    qp_max={{ .Values.libvirt_qp_max }}