apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-etc
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.enable_ceph }}
  {{ .Values.secret.rbd_secret_uuid }}.xml: |
     <secret ephemeral='no' private='no'>
     <uuid>{{ .Values.secret.rbd_secret_uuid }}</uuid>
     <usage type='ceph'>
     <name>{{ .Values.secret.secret_user }}</name>
     </usage>
     </secret>

  {{ .Values.secret.rbd_secret_uuid }}.base64: |
    {{ .Values.secret.ceph_admin_keyring }}
  {{- end }}

  libvirtd.conf: |
    listen_tcp = 1
    listen_tls = 0
    auth_tcp = "none"
    tcp_port = "16514"
    ca_file = ""
    log_level = 3
    log_outputs = "3:file:/var/log/libvirt/libvirtd.log"

  qemu.conf: |
    security_driver = "none"
    security_default_confined = 0
    user="root"
    group="root"
