apiVersion: v1
kind: ConfigMap
metadata:
  name: libvirt-etc
  namespace: {{ .Release.Namespace }}
data:
  libvirtd.conf: |
    {{- if .Values.libvirt_tls }}
    listen_tls = 1
    listen_tcp = 0
    tls_port = "{{ .Values.nova_libvirt_port }}"
    key_file = "/etc/pki/libvirt/private/serverkey.pem"
    cert_file = "/etc/pki/libvirt/servercert.pem"
    ca_file = "/etc/pki/CA/cacert.pem"
    {{- else }}
    listen_tcp = 1
    listen_tls = 0
    auth_tcp = "none"
    tcp_port = "{{ .Values.nova_libvirt_port }}"
    ca_file = ""
    {{- end }}
    log_level = 3
    log_outputs = "3:file:/var/log/kolla/libvirt/libvirtd.log"

  {{ .Values.secret.rbd_secret_uuid }}.xml: |
     <secret ephemeral='no' private='no'>
     <uuid>{{ .Values.secret.rbd_secret_uuid }}</uuid>
     <usage type='ceph'>
     <name>{{ .Values.secret.secret_user }}</name>
     </usage>
     </secret>

  {{ .Values.secret.rbd_secret_uuid }}.base64: |
    {{ .Values.secret.ceph_admin_keyring }}
