apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: btserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: btserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: btserver
    spec:
      containers:
        - name: btserver
          env:
            - name: ENV_BTSERVER_BIND_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.btserver }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: 
            - containerPort: {{ .Values.service.btserver }}
              name: btserver
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            tcpSocket:
              port: {{ .Values.service.btserver }}
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            tcpSocket:
              port: {{ .Values.service.btserver }}
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
          - name: btserver
            mountPath: {{ .Values.containerPath }}
      volumes:
      - name: btserver
        hostPath:
          path: {{ .Values.btserver_share_path }}
          type: DirectoryOrCreate
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

