apiVersion: v1
kind: Service
metadata:
  name: btserver
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.btserver }}
      targetPort: {{ .Values.service.btserver }}
      protocol: TCP
      name: btserver
  selector:
    app.kubernetes.io/name: btserver
  sessionAffinity: ClientIP