apiVersion: v1
kind: ConfigMap
metadata:
  name: btserver-etc
  namespace: {{ .Release.Namespace }}
data:
  torrent.ini: |
    [torrent]
    managementIp=0.0.0.0
    managementPort={{ .Values.service.btserver }}
    torrentIp={{ .Values.proxy_ip }}
    portBegin={{ .Values.service.btserver_start }}
    portEnd={{ .Values.service.btserver_end }}
    trackerPort={{ .Values.service.btserver_track }}
  opentracker.conf: |
    listen.udp.workers 16
    listen.tcp_udp {{ .Values.proxy_ip }}:{{ .Values.service.btserver_track }}
    tracker.user nobody
