apiVersion: apps/v1
kind: Deployment
metadata:
  name: btserver
  labels:
    {{- include "btserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "btserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "btserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "btserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: btserver
          env:
            - name: ENV_BTSERVER_BIND_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.btserver }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.btserver }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.btserver }}
          volumeMounts:
          - name: btserver
            mountPath: /mnt/voi
        - name: btserver-track
          env:
            - name: ENV_BTSERVER_BIND_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.btserver_track }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.btserver_track }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.btserver_track }}
          volumeMounts:
          - name: btserver
            mountPath: /mnt/voi
      volumes:
      - name: btserver
        hostPath:
          path: {{ .Values.btserver_share_path }}
          type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
