apiVersion: v1
kind: Service
metadata:
  name: btserver
  labels:
    {{- include "btserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.btserver }}
      targetPort: {{ .Values.service.btserver }}
      protocol: TCP
      name: btserver
    - port: {{ .Values.service.btserver_track }}
      targetPort: {{ .Values.service.btserver_track }}
      protocol: TCP
      name: btserver-track
  selector:
    {{- include "btserver.selectorLabels" . | nindent 4 }}
