apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pushgateway
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pushgateway
    spec:
      containers:
      - name: pushgateway
        args:
          - --web.listen-address=$(NODE_ID):{{ .Values.service.pushgateway.port }}
        image: {{ .Values.image.pushgateway }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: {{ .Values.service.pushgateway.port }}
          name: http
          protocol: TCP
        resources: {}
      priorityClassName: {{ .Values.priorityClassName }}
      restartPolicy: Always
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ .Values.hostNetwork }}
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
