apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: web
    port: {{ .Values.service.alertmanager.port }}
    protocol: TCP
    targetPort: web
  - name: mesh-tcp
    port: {{ .Values.service.alertmanager_cluster.port }}
    protocol: TCP
    targetPort: mesh-tcp
  - name: mesh-udp
    port: {{ .Values.service.alertmanager_cluster.port }}
    protocol: UDP
    targetPort: mesh-udp
  selector:
    app.kubernetes.io/name: alertmanager
  type: ClusterIP
