apiVersion: v1
kind: Service
metadata:
  name: event-exporter
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.event_exporter.port }}
      protocol: TCP
      targetPort: http
  selector:
    app: event-exporter