apiVersion: v1
kind: Service
metadata:
  name: collectd-exporter
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.collectd_exporter.port }}
    protocol: TCP
    targetPort: http
  - name: udp
    port: {{ .Values.service.collectd_exporter.udp_port }}
    protocol: UDP
    targetPort: udp
  selector:
    app.kubernetes.io/name: collectd-exporter
  type: ClusterIP
