apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: web
    port: {{ .Values.service.prometheus.port }}
    protocol: TCP
    targetPort: web
  - name: http-sidecar
    port: {{ .Values.service.sidecar.http_port }}
    protocol: TCP
    targetPort: http-sidecar
  - name: grpc-sidecar
    port: {{ .Values.service.sidecar.grpc_port }}
    protocol: TCP
    targetPort: grpc-sidecar
  selector:
    app.kubernetes.io/name: prometheus
  type: ClusterIP
