- name: 创建 elasticsearch values 目录
  file:
    name: /etc/kubernetes/plugins/elasticsearch
    state: directory

- name: 复制 elasticsearch charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "elasticsearch"

- name: 生成 elasticsearch values.yml
  template:
    src: custom-values-elasticsearch.yaml.j2
    dest: /etc/kubernetes/plugins/elasticsearch/values.yaml
    owner: root
    mode: 0644

- name: Install elasticsearch helm charts
  kubernetes.core.helm:
    atomic: no
    name: elasticsearch
    chart_ref: "{{ helm_charts_dir }}/elasticsearch"
    values_files:
      - /etc/kubernetes/plugins/elasticsearch/values.yaml
    state: present 
    wait: yes
    wait_timeout: "{{ helm_wait_timeout }}"
    release_namespace: "{{ helm_install_namespace }}"