- import_tasks: create_swap_file.yaml
  when:
    - create_swap_file | bool

- import_tasks: create_mount_crontab.yaml
  when:
    - enable_ceph | bool

- name: 设置 bridge-nf-call-iptables 参数
  shell: echo 0 > /proc/sys/net/bridge/bridge-nf-call-iptables
  when:
    - ansible_distribution == "openEuler"

- name: 复制开机执行脚本 reboot-script.sh
  copy:
    src: reboot-script.sh
    dest: /etc/kubernetes/reboot-script.sh
    mode: 755
  when:
    - ansible_distribution == "openEuler"

- name: 设置开机启动 iptables 命令
  become: true
  copy:
    src: iptables-accept.service
    dest: /usr/lib/systemd/system/
  when:
    - ansible_distribution == "openEuler"

- name: Reload systemctl and enable iptables-accept service
  become: true
  systemd:
    name: iptables-accept
    daemon_reload: true
    enabled: true
  when:
    - ansible_distribution == "openEuler"
