apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "websockify.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "websockify.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "websockify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "websockify.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NODE_ID
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          command:
            - websockify
          args:
            - $(NODE_ID):{{ .Values.service.port }}
            - --token-plugin=trochilus.websockify.token_plugin.Base64JsonTokenRemoteApi
            - --token-source={{ .Values.tokenSource }}
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
          resources: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "websockify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
