---
# tasks file for emqx
- name: 创建 emqx values 目录
  file:
    name: /etc/kubernetes/plugins/emqx
    state: directory

- name: 复制 emqx charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "emqx"

- name: 生成 emqx values.yml
  template:
    src: custom-values-emqx.yaml.j2
    dest: /etc/kubernetes/plugins/emqx/values.yaml
    owner: root
    mode: 0644

- name: Install emqx helm charts
  kubernetes.core.helm:
    atomic: no
    name: emqx
    chart_ref: "{{ helm_charts_dir }}/emqx"
    values_files:
      - /etc/kubernetes/plugins/emqx/values.yaml
    state: present 
    wait: yes
    wait_timeout: "{{ helm_wait_timeout }}"
    release_namespace: "{{ helm_install_namespace }}"
