- name: create emqx values dir
  file:
    name: /etc/kubernetes/plugins/emqx
    state: directory

- name: copy emqx charts dir
  copy:
    src: "emqx"
    dest: "{{ charts_dir }}/"

- name: create libvirt values.yml
  template:
    src: custom-values-emqx.yaml.j2
    dest: /etc/kubernetes/plugins/emqx/values.yaml
    owner: root
    mode: 0644


- name: Install emqx helm charts
  kubernetes.core.helm:
    atomic: no
    name: emqx
    chart_ref: "{{ charts_dir }}/emqx"
    values_files:
      - /etc/kubernetes/plugins/emqx/values.yaml
    state: present 
    wait: yes
    wait_timeout: 180

# - name: 轮询等待 libvirt 运行
#   shell: kubectl get pod --all-namespaces -o wide | grep 'libvirt' | awk '{print $4}'
#   register: libvirt_status
#   until: "'Running' in libvirt_status.stdout"
#   retries: 12
#   delay: 5
#   ignore_errors: true
