- name: 获取 mariadb host 地址
  shell: kubectl get pod -A -o wide | grep mariadb | awk -F' ' '{print $8}'
  register: mariadb_host

- block:
    - name: "Create {{ fsd_database_name }} database if don't exist"
      become: true
      mysql_db:
        login_host: "{{ mariadb_host.stdout }}"
        login_port: "3306"
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ fsd_database_name }}"
    
    - name: "Create {{ fsd_job_database_name }} database if don't exist"
      become: true
      mysql_db:
        login_host: "{{ mariadb_host.stdout }}"
        login_port: "3306"
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ fsd_job_database_name }}"

    - name: "Load {{ fsd_database_name }} sql"
      become: true
      shell: |
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_lq.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_manyanyi.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_mock.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_qjx.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_wzy.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_wzy.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_database_name }} < {{ role_path }}/files/sql/klcloud_fsd_yuanwei.sql
        mysql -h{{ mariadb_host.stdout }} -uroot -p{{ mariadb_root_password }} {{ fsd_job_database_name }} < {{ role_path }}/files/sql/xxl_job.sql

  run_once: True