- name: 创建 fsd values 目录
  file:
    name: /etc/kubernetes/plugins/fsd
    state: directory

- name: 复制 fsd charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "fsd"

- name: 生成 fsd values.yml
  template:
    src: custom-fsd-values.yaml.j2
    dest: /etc/kubernetes/plugins/fsd/values.yaml
    owner: root
    mode: 0644

- name: Install fsd helm charts
  kubernetes.core.helm:
    atomic: no
    name: fsd
    chart_ref: "{{ helm_charts_dir }}/fsd"
    values_files:
      - /etc/kubernetes/plugins/fsd/values.yaml
    state: present 
    wait: yes
    wait_timeout: 200s
    release_namespace: "{{ helm_install_namespace }}"
