---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guest-service-config
  namespace: {{ .Release.Namespace }}
data:
  guest_service.conf: |
    [DEFAULT]
    mqtt_server = {{ .Values.mqttVip }}
    mqtt_port = {{ .Values.mqttPort }}
    prometheus_url = {{ .Values.prometheus_url }}