---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guest-service-config
  namespace: {{ .Release.Namespace }}
data:
  guest_service.conf: |
    [DEFAULT]
    mqtt_server = {{ .Values.emqx_svc_name }}
    mqtt_port = {{ .Values.emqx_port }}
    prometheus_url = {{ .Values.pushgateway_svc_name }}
