apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: guest-service
    app.kubernetes.io/component: guest-service
    app.kubernetes.io/release_group: guest-service
  name: guest-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: guest-service
      app.kubernetes.io/component: guest-service
      app.kubernetes.io/release_group: guest-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guest-service
        app.kubernetes.io/component: guest-service
        app.kubernetes.io/release_group: guest-service
    spec:
      containers:
        - name: guest-service
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: configfile
              subPath: guest_service.conf
              mountPath: /etc/guest-service/guest_service.conf
            - name: var-lib-libvirt
              mountPath: /var/lib/libvirt
              mountPropagation: Bidirectional
            - name: var-run-libvirt
              mountPath: /var/run/libvirt
              mountPropagation: Bidirectional   
            - name: var-log 
              mountPath: /var/log/guest-service/
              mountPropagation: Bidirectional 
          resources:
          {{- toYaml .Values.resources | nindent 12 }}   
      volumes:
        - name: configfile
          configMap:
            name: guest-service-config
        - name: var-lib-libvirt
          hostPath:
            path: /var/lib/libvirt
            type: ""
        - name: var-run-libvirt
          hostPath:
             path: /var/run/libvirt
             type: ""
        - name: var-log
          hostPath:
             path: /var/log/guest-service/
             type: DirectoryOrCreate
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.pullSecrets }}
      {{- end }}
