- import_tasks: generate_ceph_config.yaml
  when:
    - enable_ceph | bool

- name: undefine libvirt 网络
  shell: virsh net-undefine default
  ignore_errors: true
  when:
    - ansible_distribution == "openEuler"

- name: 创建 vdi 目录
  file:
    path: /etc/vdi/
    state: directory
    mode: 0755

- name: Copy vdi.ini 文件
  copy:
    src: vdi_conf.ini
    dest: /etc/vdi/vdi_conf.ini
    owner: root
    mode: 0644

- import_tasks: libvirt-install.yaml
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"
