image:
  mariadb: bitnami/mariadb:10.5.15-debian-10-r52
  pullSecrets: ""
mariadb_password: 123456
storageclass: cephfs-general
pvc:
  name: mariadb
  size: 10Gi
tolerationSeconds: 30

service:
  mariadb:
    name: mysql
    port: 3306

nodeSelector:
  control_role: enabled
ingress:
  enabled: true
  ingressClassName: nginx
priorityClassName: ""
