image:
  mariadb: bitnami/mariadb:10.5.15-debian-10-r52
  mysqldump: bitnami/mariadb:10.5.15-debian-10-r52
  pullSecrets: ""
mariadb_password: 123456
mariadb_connection: 30000
hostNetwork: true
persistentVolume:
  enabled: true
  name: mariadb
  size: 10Gi
  storageclass: cephfs-general
tolerationSeconds: 30
service:
  mariadb:
    name: mysql
    port: 3306
nodeSelector:
  control_role: enabled
ingress:
  enabled: true
  ingressClassName: nginx
priorityClassName: ""
mariadb_host_path: /var/lib/mariadb
mariadb_backup_path: /var/lib/mariadb-backup
affinity:
  key: control_role
  value: enabled
mysqldump:
  cron: "* 1 * * *"
  history:
    success: 3
    failed: 1