- name: 创建 prometheus values 目录
  file:
    name: /etc/kubernetes/plugins/prometheus
    state: directory
  
- name: 复制 prometheus charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "prometheus"

- name: 生成 prometheus values.yml
  template:
    src: custom-values-prometheus.yaml.j2
    dest: /etc/kubernetes/plugins/prometheus/values.yaml
    owner: root
    mode: 0644

- name: Install prometheus helm charts
  kubernetes.core.helm:
    atomic: no
    name: prometheus
    chart_ref: "{{ helm_charts_dir }}/prometheus"
    values_files:
      - /etc/kubernetes/plugins/prometheus/values.yaml
    state: present 
    wait: yes
    wait_timeout: 300s
    release_namespace: "{{ helm_install_namespace }}"
