desktop_mount_shell_dir: "/etc/ceph/cephmount"
cephmount_service_dir: "/usr/lib/systemd/system/"
fsd_cloud_disk_root_path: "{{ desktop_mount_dir }}/111"
fsd_cloud_disk_share_disk_path: "ShareA"
fsd_voi_dir: "{{ desktop_mount_dir }}/voi"
fsd_voi_upload_dir: "{{ desktop_mount_dir }}/upload"
fsd_static_dir: /var/nginx/nginx_page/static
fsd_log: /var/log/fsd
init_sql_dir: /tmp/fsd
ceph_local_ip: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"
fsd_netty_codec_mac: "{{ ansible_default_ipv4.macaddress | replace(':', '')}}"
prometheus_alert_rule_dir: "{{ desktop_mount_dir }}/prometheus/rules"
prometheus_alertmanager_dir: "{{ desktop_mount_dir }}/prometheus/alertmanager"
replicaNum: "{% if groups['fsd'] | length > 2 %}3{% else %}1{% endif %}"
proxy_ip: "{% if fsd_proxy_ip %}{{ fsd_proxy_ip }}{% else %}{{ kube_apiserver_vip }}{% endif %}"