- hosts: 
  - all
  roles:
  - prepare/base
  - prepare/container

# 安装 load-balancer
- hosts:
  - all
  roles:
  - load-balancer

# 初始化master节点
- hosts:
  - kube-master
  - new-master
  roles:
  - kube-master

# 初始化worker节点
- hosts:
  - kube-worker
  - new-worker
  roles:
  - kube-worker

# # 安装集群插件
- hosts:
  - kube-master
  roles:
  - plugins
