# - hosts: 
#   - allnodes
#   roles:
#   - prepare/base
#   - prepare/container

# # 安装 load-balancer
# - hosts:
#   - allnodes
#   roles:
#   - load-balancer

# # 初始化master节点
# - hosts:
#   - kube-master
#   - new-master
#   roles:
#   - kube-master

# # 初始化worker节点
# - hosts:
#   - kube-worker
#   - new-worker
#   roles:
#   - kube-worker

# - hosts:
#   - allnodes
#   roles:
#   - ceph-csi

- hosts:
  - allnodes
  roles:
  - mariadb

- hosts:
  - compute
  roles:
  - libvirt

- hosts:
  - trochilus
  roles:
  - trochilus

- hosts:
  - prometheus
  roles:
  - prometheus
