apiVersion: v1
kind: Service
metadata:
  name: fsd
spec:
  ports:
    - port: {{ .Values.service.fsd_webhook.port }}
      targetPort: {{ .Values.service.fsd_webhook.port }}
      name: {{ .Values.service.fsd_webhook.name }}
    - port: {{ .Values.service.fsd_tcp.port }}
      targetPort: {{ .Values.service.fsd_tcp.port }}
      name: {{ .Values.service.fsd_tcp.name }}
  selector:
    type: fsd
  type: ClusterIP