apiVersion: v1
kind: Service
metadata:
  name: fsd-nginx
spec:
  ports:
    - port: {{ .Values.service.fsd_nginx.port }}
      targetPort: {{ .Values.service.fsd_nginx.port }}
      name: {{ .Values.service.fsd_nginx.name }}
  selector:
    fsd: web
  type: ClusterIP
