apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsd-job
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      type: fsd-job
  strategy:
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: fsd-job
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                    - fsd-job
              topologyKey: 'kubernetes.io/hostname'
      containers:
        - name: fsd-job
          image: {{ .Values.image.fsd_job }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.fsd_job.port }}
              protocol: TCP
              name: {{ .Values.service.fsd_job.name }}
          env:
            - name: ENV_FSD_COMMON_JOB_MYSQL_HOST
              value: "{{ .Values.fsd_job_env.mariadb_host }}"
            - name: ENV_FSD_COMMON_JOB_MYSQL_USERNAME
              value: "{{ .Values.fsd_job_env.mariadb_username }}"
            - name: ENV_FSD_COMMON_JOB_MYSQL_PASSWORD
              value: "{{ .Values.fsd_job_env.mariadb_password }}"
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      serviceAccount: {{ .Values.serviceAccountName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
