apiVersion: v1
kind: ConfigMap
metadata:
  name: fsd-etc
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections  10240;
      multi_accept on;
    }

    http {
      include mime.types;
      default_type application/octet-stream;

      client_header_buffer_size 4k;
      proxy_headers_hash_max_size 51200;
      proxy_headers_hash_bucket_size 6400;

      client_max_body_size 100g;
      proxy_max_temp_file_size 0;

      sendfile           on;
      keepalive_timeout  65;
      server_tokens off;

      log_format aka_logs
        '{"@timestamp":"$time_local",'
        '"log_date":"$msec",'
        '"domain":"$host",'
        '"server_ip":"$server_addr",'
        '"server_port":"$server_port",'
        '"client_ip":"$remote_addr",'
        '"client_port":"$remote_port",'
        '"size":"$body_bytes_sent",'
        '"responsetime":"$request_time",'
        '"upstreamtime":"$upstream_response_time",'
        '"request_method":"$request_method",'
        '"url":"$uri",'
        '"http_version":"$http_version",'
        '"http_platform":"$http_platform",'
        '"http_deviceid":"$http_deviceid",'
        '"http_language":"$http_language",'
        '"http_content_type":"$http_content_type",'
        '"http_deviceinfo":"$http_deviceinfo",'
        '"http_user_agent":"$http_user_agent",'
        '"status":"$status",'
        '"referer":"$http_referer"'
      '}';

      access_log /var/log/nginx/access.log aka_logs;
      error_log /var/log/nginx/error.log debug;

      include "/etc/nginx/conf/*.conf";

    }
  fsd.conf: |
    server {
      listen       {{ .Values.service.fsd_web.port }};
      server_name  {{ .Values.fsd_env.deploy_vip }};
      gzip on;
      gzip_min_length 100;
      gzip_types text/plain text/css application/xml application/javascript;
      gzip_vary on;
            
      location / {
        root    /usr/local/nginx_page/;
        index   index.php index.html index.htm;
      }
      
      #vue hash路由刷新页面会把第一个api接口赋予20080端口导致404，所以做一层转发
      location /api/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://{{ .Values.fsd_env.deploy_vip }}:{{ .Values.service.fsd_webhook.port }}/api/;
      }
    }
