apiVersion: v1
kind: Service
metadata:
  name: fsd-job
spec:
  ports:
    - port: {{ .Values.service.fsd_job.port }}
      targetPort: {{ .Values.service.fsd_job.port }}
      name: {{ .Values.service.fsd_job.name }}
  selector:
    type: fsd-job
  type: ClusterIP