apiVersion: v1
kind: Service
metadata:
  name: fsd-nginx
  annotations:
    metallb.universe.tf/address-pool: address-pool
    metallb.universe.tf/allow-shared-ip: address-pool
spec:
  ports:
    - port: {{ .Values.service.fsd_nginx.port }}
      targetPort: {{ .Values.service.fsd_nginx.port }}
      name: {{ .Values.service.fsd_nginx.name }}
  selector:
    fsd: web
  type: LoadBalancer
