{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: mariadb
    http:
      paths:
      - backend:
          service:
            name: mariadb
            port:
              name: mysql
        path: /
        pathType: ImplementationSpecific
  - host: mariadb.{{ .Release.Namespace }}
    http:
      paths:
      - backend:
          service:
            name: mariadb
            port:
              name: mysql
        path: /
        pathType: ImplementationSpecific
  - host: mariadb.{{ .Release.Namespace }}.svc.cluster.local
    http:
      paths:
      - backend:
          service:
            name: mariadb
            port:
              name: mysql
        path: /
        pathType: ImplementationSpecific
{{- end }}