apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - extensions
  - batch
  - apps
  resources:
  - pods
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb
subjects:
- kind: ServiceAccount
  name: mariadb
  namespace: {{ .Release.Namespace }}