apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/release_group: mariadb
  type: ClusterIP
