apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.mariadb.name }}
    port: {{ .Values.service.mariadb.port }}
    protocol: TCP
    targetPort: {{ .Values.service.mariadb.name }}
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/release_group: mariadb
    app: mariadb
  type: ClusterIP
